#!/bin/bash

source_dir="$HOME/work/arangodb"
build_dir="$HOME/work/arangodb-build"
data_dir="$HOME/work/arangodb-data/"
data_conf="$HOME/work/arangodb-conf/"

port=8529

cd "$source_dir"
clear

"$build_dir/bin/arangod" \
    --configuration none \
    --javascript.startup-directory js \
    --javascript.app-path "js/apps" \
    --server.endpoint tcp://localhost:$port \
    --database.directory "$data_dir"
rv=$?


if (( rv != 0 )); then
    echo
    echo
    echo
    echo
    echo "failed to start database!"
fi

exit $rv
