#!/bin/bash

source scripts-lib.bash

vpack_invalid(){
    curl -X POST http://$server/_admin/echo --header "Content-Type: application/x-velocypack" --data-binary "dfafas dsf"
}



case $1 in
    js)
        echo "JavaScript used for Request"
        curl -X GET http://$server/_admin/time --dump - --header "Accept:application/x-velocypack"
        echo
    ;;
    vpacki*)
        vpack_invalid
    ;;
    *)
        echo "default case:"
        echo "return json:"
        curl -XPOST http://$server/_api/document?collection=test -d '{ "foo" : "bar"  }'
        echo "--------"
        echo "return velocypack:"
        #ramtmp="$(mktemp -p /dev/shm/)"
        ramtmp="/dev/shm/tmp.v2j"
        curl -XPOST http://$server/_api/document?collection=test -d '{ "foo" : "bar"  }' --header "Accept: application/x-velocypack" > "$ramtmp"
        echo "plain:"
        cat "$ramtmp"
        echo
        echo "--------"
        echo "hexdump:"
        hexdump -C < "$ramtmp"
        echo
        echo "--------"
        echo "v2j:"
        ./v2j < $ramtmp
        echo
    ;;
esac
