#!/bin/bash

source scripts-lib.bash

cd $source_dir

program="arangod"

if [[ -n $1 ]]; then
    cmd_file="$1"
else
    cmd_file="$helper_dir/vpack.gdb"
fi

set -x
gdb -command="$cmd_file" --args "$binary_dir/arangod" "$data_dir" --server.endpoint vpp+tcp://localhost:8529 --log.level communication=debug
set +x
echo "gdb -command=$cmd_file --args $binary_dir/arangod $data_dir --server.endpoint vpp+tcp://localhost:8529"

