#!/bin/bash

source scripts-lib.bash

cd "$source_dir"

#scripts/unittest http_server --server tcp://$server_ip:server_port/ --test api-export-spec-timecritical-noncluster.rb
scripts/unittest http_server --test api-export-spec-timecritical-noncluster.rb
