#!/bin/bash

cmd=()
args=()

#debugger
gdb=false
rr=false
massif=false

# general settigns
engine="rocksdb"
port=8529
directory="default"

# options that ease debugging
authentication=false
statistics=false
queues=false

#logging
extra_logging=false
log_direct=true
log_thread=true

#parse args
while [[ -n $1 ]]; do
    case "$1" in
        --dir)
            directory="$2"
            shift 2
        ;;
        --gdb)
            gdb=true
            shift
        ;;
        --rr)
            rr=true
            shift
        ;;
        --massif)
            massif=true
            shift
        ;;
        --rocksdb)
            engine="rocksdb"
            shift
        ;;
        --mmfiles)
            engine="mmfiles"
            shift
        ;;
        --auth)
            authentication=true
            shift
        ;;
        --no-direct)
            log_direct=false
            shift
        ;;
        --statistics)
            statistics=true
            shift
        ;;
        --port)
            port=$2
            shift 2
        ;;
        *)
            args+=( "$1" )
            shift
    esac
done

cdir=$(pwd)
dirprefix=${cdir%/*}
dirname=${cdir##*/}

mkdir -p "${cdir}-data"

if $gdb; then
  cmd+=( 'gdb' '--args' )
fi

if $rr; then
  cmd+=( 'rr' )
fi

if $massif; then
  echo "starting with massif"
  cmd+=( 'valgrind' '--tool=massif'
         '--depth=50' '--detailed-freq=1'
        # '--time-unit=ms'
         '--vgdb=yes'
       )
fi

for p in $port 5555 7777 8888 9999; do
    if ! nc -z localhost $p ; then
        port=$p
        echo "found free port: $p"
        break
    fi
done

echo "using port $port"

exe_path="./build/bin/arangod"

if [[ ! -x "$exe_path" ]]; then
    echo "exectuable can not be found at $exe_path"
    exit 1
fi

cmd+=( "$exe_path" )
cmd+=(
    '--server.endpoint' "http+tcp://0.0.0.0:$port"
    '--server.authentication' "$authentication"
    '--server.statistics' "$statistics"
    '--server.storage-engine' "$engine"
    '--foxx.queues' "$queues"
    '--temp.path' "/tmp/obi-$(date +%T)/"
    '--log.force-direct' "$log_direct"
    '--log.foreground-tty' 'true'
    '--log.thread' "$log_thread"
    "${args[@]}"
)

if $extra_logging; then
    cmd+=(
        '--log.level' 'communication=trace'
        '--log.level' 'requests=trace'
        '--log.level' 'fixme=trace'
    )
fi

cmd+=( "${cdir}-data/${directory}_${engine}" )

echo "${cmd[@]}"
"${cmd[@]}"
