#!/bin/bash

cmd=()

gdb=false
massif=false
extra_logging=false
authentication=false
log_direct=false
engine="rocksdb"
port=8529

cdir=$(pwd)
dirprefix=${cdir%/*}
dirname=${cdir##*/}

mkdir -p "${cdir}-data"

if $gdb; then
  cmd+=( 'gdb' '--args' )
fi

if $massif; then
  echo "starting with massif"
  cmd+=( 'valgrind' '--tool=massif'
         '--depth=50' '--detailed-freq=1'
        # '--time-unit=ms'
         '--vgdb=yes'
       )
fi

for p in 8529 5555 7777 8888 9999; do
    if ! nc -z localhost $p ; then
        port=$p
        echo "found free port: $p"
        break
    fi
done

echo "using port $port"

cmd+=( './build/bin/arangod' )
cmd+=(
    '--server.endpoint' "http+tcp://0.0.0.0:$port"
    '--server.authentication' "$authentication"
    '--server.statistics' 'false'
    '--server.storage-engine' "$engine"
    '--foxx.queues' 'false'
    '--temp.path' "/tmp/obi-$(date +%T)/"
    '--log.force-direct' "$log_direct"
    '--console'
)

if $extra_logging; then
    cmd+=(
        '--log.level' 'communication=trace'
        '--log.level' 'requests=trace'
    )
fi

cmd+=( "${cdir}-data/rocks-server" )

echo "${cmd[@]}"
"${cmd[@]}"
