#!/bin/bash

source scripts-lib.bash

clear

"$build_dir/bin/arangod" \
    --console \
    --configuration none \
    --javascript.startup-directory js \
    --javascript.app-path "js/apps" \
    --server.endpoint tcp://$server \
    --server.authentication false \
    --database.directory "$data_dir"
rv=$?


if (( rv != 0 )); then
    echo
    echo "failed to start database!"
fi

exit $rv
