#!/bin/bash

cmd=()

gdb=false
massif=false
extra_logging=false
authentication=false
port=5555

cdir=$(pwd)
dirprefix=${cdir%/*}
dirname=${cdir##*/}

if $gdb; then
  cmd+=( 'gdb' '--args' )
fi

if $massif; then
  echo "starting with massif"
  cmd+=( 'valgrind' '--tool=massif'
         '--depth=50' '--detailed-freq=1'
         '--time-unit=ms'
       )
fi

for p in 5555 7777 8888 9999; do
    if ! grep 0.0.0.0:$p < <(netstat -nlpt); then
        port=$p
        break
    fi
done

cmd+=( './build/bin/arangod' )
cmd+=(
    '--server.endpoint' "http+tcp://0.0.0.0:$port"
    '--server.authentication' "$authentication"
    '--server.statistics' 'false'
    '--server.storage-engine' 'rocksdb'
    '--foxx.queues' 'false'
    '--console'
    '--temp.path' "/tmp/obi-$(date +%T)/"
)

if $extra_logging; then
    cmd+=(
        '--log.level' 'communication=trace'
        '--log.level' 'requests=trace'
    )
fi

cmd+=( "${cdir}-data-rocks-server" )

echo "${cmd[@]}"
"${cmd[@]}"
