#!/bin/bash

cmd=()

#debugger
gdb=false
massif=false

# general settigns
engine="rocksdb"
port=8529

# options that ease debugging
authentication=false
statistics=false
queues=false

#logging
extra_logging=false
log_direct=true
log_thread=true

#parse args
while [[ -n $1 ]]; do
    case "$1" in
        --rocksdb)
            shift
            engine="rocksdb"
        ;;
        --mmfiles)
            shift
            engine="mmfiles"
        ;;
    esac
done

cdir=$(pwd)
dirprefix=${cdir%/*}
dirname=${cdir##*/}

mkdir -p "${cdir}-data"

if $gdb; then
  cmd+=( 'gdb' '--args' )
fi

if $massif; then
  echo "starting with massif"
  cmd+=( 'valgrind' '--tool=massif'
         '--depth=50' '--detailed-freq=1'
        # '--time-unit=ms'
         '--vgdb=yes'
       )
fi

for p in 8529 5555 7777 8888 9999; do
    if ! nc -z localhost $p ; then
        port=$p
        echo "found free port: $p"
        break
    fi
done

echo "using port $port"

exe_path="./build/bin/arangod"

if [[ ! -x "$exe_path" ]]; then
    echo "exectuable can not be found at $exe_path"
    exit 1
fi

cmd+=( "$exe_path" )
cmd+=(
    '--server.endpoint' "http+tcp://0.0.0.0:$port"
    '--server.authentication' "$authentication"
    '--server.statistics' "$statistics"
    '--server.storage-engine' "$engine"
    '--foxx.queues' "$queues"
    '--temp.path' "/tmp/obi-$(date +%T)/"
    '--log.force-direct' "$log_direct"
    '--log.thread' "$log_thread"
    '--console'
)

if $extra_logging; then
    cmd+=(
        '--log.level' 'communication=trace'
        '--log.level' 'requests=trace'
        '--log.level' 'fixme=trace'
    )
fi

cmd+=( "${cdir}-data/${engine}-server" )

echo "${cmd[@]}"
"${cmd[@]}"
